### ISSUE TITLE
Smithing Bugs

### ISSUE THREAD

**Issue by PrimusOmega** [WoodenTucker/40K-Eipharius#336]
I've done a quick test of some of the new recipes.  Here are a few of the bugs I've found.

The recipe for Ingot Lube in fact creates a Hammer instead.
The recipe lists for Diamantine and Kultrinium appear to be broken, and output the recipe list for Gold instead.  I assume Titanite will likely be the same, though Cobalt did function correctly.

**Comment by ZAB909** [comment]
The bug fixes are currently on my local and planned to be made soon. Intended features atm that will be hotfixed, basically
